#nullable enable
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
/// <summary>
/// RecipientResolver service for alert management system.
/// </summary>
using System;
using System.Collections.Generic;
using System.Linq;
using VanDijk.AlertManagement.Core.Interfaces;

public class RecipientResolver : IRecipientResolver, IRecipientListProvider
{
    private readonly IRoutingStrategy _routingStrategy;
    private readonly RecipientStorage _recipientStorage;

    public RecipientResolver(IRoutingStrategy routingStrategy, RecipientStorage recipientStorage)
    {
        _routingStrategy = routingStrategy;
        _recipientStorage = recipientStorage;
    }

    public void RefreshRecipients()
    {
        var recipients = _recipientStorage.LoadRecipients();
        if (_routingStrategy is RecipientRoutingStrategy rrs)
        {
            rrs.UpdateRecipients(recipients);
        }
    }

    public Recipient ResolveRecipient(Alert alert)
    {
        RefreshRecipients();
        var recipient = _routingStrategy.DetermineRecipient(alert);
        if (recipient == null)
            throw new InvalidOperationException("No recipient could be resolved for the given alert.");
        return recipient;
    }

    public IRoutingStrategy RoutingStrategy => _routingStrategy;

    public IEnumerable<Recipient> GetAllRecipients()
    {
        if (_routingStrategy is RecipientRoutingStrategy rrs)
            // Pass a default or specific component value instead of null
            return rrs.GetRecipientsForComponent(string.Empty);
        return Enumerable.Empty<Recipient>();
    }
}
